spring.application.name=Smart_System_Optimizer

#  SQLite Config
spring.datasource.url=jdbc:sqlite:optimizer.db
spring.datasource.driver-class-name=org.sqlite.JDBC

#  Hibernate Config
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#  VERY IMPORTANT (fixes startup issue)
spring.jpa.open-in-view=false

#  Optional but recommended
spring.datasource.hikari.maximum-pool-size=1






server.port=8080

# Allow external access (important for Electron)
server.address=0.0.0.0

# Disable dev tools in production
spring.devtools.restart.enabled=false